using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Castlevania___HoD__Save_Editor_
{
    partial class Form1
    {

        public void loadArmors()
        {
            armorsInput.Rows.Add("Leather Armor", 0);
            armorsInput.Rows.Add("Rubber Armor", 0);
            armorsInput.Rows.Add("Field Armor", 0);
            armorsInput.Rows.Add("Plate Coat", 0);
            armorsInput.Rows.Add("Cloth Tunic", 0);
            armorsInput.Rows.Add("Bronze Armor", 0);
            armorsInput.Rows.Add("Rock Leather", 0);
            armorsInput.Rows.Add("Cuirass Armor", 0);
            armorsInput.Rows.Add("Padded Armor", 0);
            armorsInput.Rows.Add("Pluff Coat", 0);
            armorsInput.Rows.Add("Parade Armor", 0);
            armorsInput.Rows.Add("Chain Mail", 0);
            armorsInput.Rows.Add("Scale Armor", 0);
            armorsInput.Rows.Add("Healing Mail", 0);
            armorsInput.Rows.Add("Guardian Armor", 0);
            armorsInput.Rows.Add("Fire Mail", 0);
            armorsInput.Rows.Add("Brigandine", 0);
            armorsInput.Rows.Add("Ancient Armor", 0);
            armorsInput.Rows.Add("Heavy Armor", 0);
            armorsInput.Rows.Add("Plate Mail", 0);
            armorsInput.Rows.Add("Double Mail", 0);
            armorsInput.Rows.Add("Sun Armor", 0);
            armorsInput.Rows.Add("Moon Armor", 0);
            armorsInput.Rows.Add("Battle Armor", 0);
            armorsInput.Rows.Add("Walk Armor", 0);
            armorsInput.Rows.Add("Silver Armor", 0);
            armorsInput.Rows.Add("Ceramic Mail", 0);
            armorsInput.Rows.Add("Magical Armor", 0);
            armorsInput.Rows.Add("Kaiser Mail", 0);
            armorsInput.Rows.Add("Casual Wear", 0);
            armorsInput.Rows.Add("Summer Clothes", 0);
            armorsInput.Rows.Add("T - Shirt", 0);
            armorsInput.Rows.Add("Thin Robe", 0);
            armorsInput.Rows.Add("Fancy Clothes", 0);
            armorsInput.Rows.Add("Loose Clothing", 0);
            armorsInput.Rows.Add("Ramail Coat", 0);
            armorsInput.Rows.Add("Blizzard Robe", 0);
            armorsInput.Rows.Add("Noble Robe", 0);
            armorsInput.Rows.Add("Mystical Robe", 0);
            armorsInput.Rows.Add("Lightning Robe", 0);
            armorsInput.Rows.Add("War Fatigues", 0);
            armorsInput.Rows.Add("Ancient Robe", 0);
        }

        public void loadAccessories()
        {
            accessoriesInput.Rows.Add("JB's Bracelet", 0);
            accessoriesInput.Rows.Add("Night Goggles", 0);
            accessoriesInput.Rows.Add("MK's Bracelet", 0);
            accessoriesInput.Rows.Add("Crush Boots", 0);
            accessoriesInput.Rows.Add("Fancy Bandana", 0);
            accessoriesInput.Rows.Add("Sturdy Turban", 0);
            accessoriesInput.Rows.Add("Plain Circlet", 0);
            accessoriesInput.Rows.Add("Leather Cap", 0);
            accessoriesInput.Rows.Add("Cloth Helmet", 0);
            accessoriesInput.Rows.Add("Leather Helmet", 0);
            accessoriesInput.Rows.Add("Sallet", 0);
            accessoriesInput.Rows.Add("Bicocette", 0);
            accessoriesInput.Rows.Add("Greek Helm", 0);
            accessoriesInput.Rows.Add("Face-guard", 0);
            accessoriesInput.Rows.Add("Piros Helm", 0);
            accessoriesInput.Rows.Add("Bagonette", 0);
            accessoriesInput.Rows.Add("Barbuta", 0);
            accessoriesInput.Rows.Add("Guardian Helm", 0);
            accessoriesInput.Rows.Add("Armet", 0);
            accessoriesInput.Rows.Add("Bascinet", 0);
            accessoriesInput.Rows.Add("Silk Hat", 0);
            accessoriesInput.Rows.Add("Barrel Helmet", 0);
            accessoriesInput.Rows.Add("Morion", 0);
            accessoriesInput.Rows.Add("Kettle Hat", 0);
            accessoriesInput.Rows.Add("Iron Helmet", 0);
            accessoriesInput.Rows.Add("Full Helmet", 0);
            accessoriesInput.Rows.Add("Cabacete", 0);
            accessoriesInput.Rows.Add("Pot Helm", 0);
            accessoriesInput.Rows.Add("Silver Tiara", 0);
            accessoriesInput.Rows.Add("Steel Helmet", 0);
            accessoriesInput.Rows.Add("Viking Helm", 0);
            accessoriesInput.Rows.Add("Gold Headband", 0);
            accessoriesInput.Rows.Add("Platinum Crown", 0);
            accessoriesInput.Rows.Add("Red Silk Hat", 0);
            accessoriesInput.Rows.Add("Leather Gloves", 0);
            accessoriesInput.Rows.Add("Gauntlets", 0);
            accessoriesInput.Rows.Add("Gloves", 0);
            accessoriesInput.Rows.Add("Hard Gloves", 0);
            accessoriesInput.Rows.Add("Guardian Glove", 0);
            accessoriesInput.Rows.Add("Arm Guards", 0);
            accessoriesInput.Rows.Add("Arm Plates", 0);
            accessoriesInput.Rows.Add("Bloody Glove", 0);
            accessoriesInput.Rows.Add("Steel Glove", 0);
            accessoriesInput.Rows.Add("Leather Boots", 0);
            accessoriesInput.Rows.Add("Shin Guards", 0);
            accessoriesInput.Rows.Add("Ankle Guards", 0);
            accessoriesInput.Rows.Add("Bronze Boots", 0);
            accessoriesInput.Rows.Add("Guardian Boots", 0);
            accessoriesInput.Rows.Add("Iron Boots", 0);
            accessoriesInput.Rows.Add("Greaves", 0);
            accessoriesInput.Rows.Add("Leggings", 0);
            accessoriesInput.Rows.Add("Silver Boots", 0);
            accessoriesInput.Rows.Add("Floating Boots", 0);
            accessoriesInput.Rows.Add("Platinum Boots", 0);
            accessoriesInput.Rows.Add("Infinite Boots", 0);
            accessoriesInput.Rows.Add("Silk Cloak", 0);
            accessoriesInput.Rows.Add("Velvet Cload", 0);
            accessoriesInput.Rows.Add("Emerald Cloak", 0);
            accessoriesInput.Rows.Add("Wind Cloak", 0);
            accessoriesInput.Rows.Add("Crimson Cloak", 0);
            accessoriesInput.Rows.Add("Ninja Cloak", 0);
            accessoriesInput.Rows.Add("Twilight Cloak", 0);
            accessoriesInput.Rows.Add("Wirstband", 0);
            accessoriesInput.Rows.Add("Bangle", 0);
            accessoriesInput.Rows.Add("Kaiser Knuckle", 0);
            accessoriesInput.Rows.Add("Silver Bangle", 0);
            accessoriesInput.Rows.Add("Crested Band", 0);
            accessoriesInput.Rows.Add("Pendant", 0);
            accessoriesInput.Rows.Add("Lucky Charm", 0);
            accessoriesInput.Rows.Add("Gold Necklace", 0);
            accessoriesInput.Rows.Add("Magic Necklace", 0);
            accessoriesInput.Rows.Add("Medusa Pendant", 0);
            accessoriesInput.Rows.Add("Heart Chocker", 0);
            accessoriesInput.Rows.Add("Greed Amulet", 0);
            accessoriesInput.Rows.Add("Mystic Brooch", 0);
            accessoriesInput.Rows.Add("Cipher's Charm", 0);
            accessoriesInput.Rows.Add("Mirror Pendant", 0);
            accessoriesInput.Rows.Add("Lucky Ring", 0);
            accessoriesInput.Rows.Add("Holy Ring", 0);
            accessoriesInput.Rows.Add("Rare Ring", 0);
            accessoriesInput.Rows.Add("Chaos Ring", 0);
            accessoriesInput.Rows.Add("Nova Ring", 0);
            accessoriesInput.Rows.Add("Logoth's Ring", 0);
            accessoriesInput.Rows.Add("Heaven's Ring", 0);
            accessoriesInput.Rows.Add("Aurora Ring", 0);
            accessoriesInput.Rows.Add("Earth Ring", 0);
        }

        public void loadItems()
        {
            itemsInput.Rows.Add("Potion", 0);
            itemsInput.Rows.Add("High Potion", 0);
            itemsInput.Rows.Add("Elixir", 0);
            itemsInput.Rows.Add("Mana Prism", 0);
            itemsInput.Rows.Add("Big Mana Prism", 0);
            itemsInput.Rows.Add("Drumstick", 0);
            itemsInput.Rows.Add("Turkey", 0);
            itemsInput.Rows.Add("Anti-venom", 0);
            itemsInput.Rows.Add("Uncurse Potion", 0);
            itemsInput.Rows.Add("Medecine Jar", 0);
            itemsInput.Rows.Add("Lure Key", 0);
            itemsInput.Rows.Add("Skull Key", 0);
            itemsInput.Rows.Add("Floodgate Key", 0);
            itemsInput.Rows.Add("Castle Map 1", 0);
            itemsInput.Rows.Add("Castle Map 2", 0);
            itemsInput.Rows.Add("Castle Map 3", 0);
            itemsInput.Rows.Add("Hint Cart 1", 0);
            itemsInput.Rows.Add("Hint Cart 2", 0);
            itemsInput.Rows.Add("Hint Cart 3", 0);
            itemsInput.Rows.Add("Hint Cart 4", 0);
            itemsInput.Rows.Add("Hint Cart 5", 0);
            itemsInput.Rows.Add("Hint Cart 6", 0);
            itemsInput.Rows.Add("Noon Star", 0);
            itemsInput.Rows.Add("Opal", 0);
            itemsInput.Rows.Add("Turquoise", 0);
            itemsInput.Rows.Add("Sapphire", 0);
            itemsInput.Rows.Add("Ruby", 0);
            itemsInput.Rows.Add("Diamond", 0);
        }

        public void loadEncyclopedia()
        {
            encyclopediaInput.Rows.Add("Bat", 0);
            encyclopediaInput.Rows.Add("Tiny Slime", 0);
            encyclopediaInput.Rows.Add("Slime", 0);
            encyclopediaInput.Rows.Add("Medusa Head", 0);
            encyclopediaInput.Rows.Add("Zombie", 0);
            encyclopediaInput.Rows.Add("Skeleton", 0);
            encyclopediaInput.Rows.Add("Fleaman", 0);
            encyclopediaInput.Rows.Add("Bone Soldier", 0);
            encyclopediaInput.Rows.Add("Armor Knight", 0);
            encyclopediaInput.Rows.Add("Giant Bat", 0);
            encyclopediaInput.Rows.Add("Ghost", 0);
            encyclopediaInput.Rows.Add("Bone Pillar", 0);
            encyclopediaInput.Rows.Add("Large Ghost", 0);
            encyclopediaInput.Rows.Add("White Dragon", 0);
            encyclopediaInput.Rows.Add("Rock Armor", 0);
            encyclopediaInput.Rows.Add("White Dragon Lv2", 0);
            encyclopediaInput.Rows.Add("Lizard Man", 0);
            encyclopediaInput.Rows.Add("Living Armor", 0);
            encyclopediaInput.Rows.Add("Ectoplasm", 0);
            encyclopediaInput.Rows.Add("Skeleton Blaze", 0);
            encyclopediaInput.Rows.Add("Big Skeleton", 0);
            encyclopediaInput.Rows.Add("Flying Bone", 0);
            encyclopediaInput.Rows.Add("Peeping Eye", 0);
            encyclopediaInput.Rows.Add("Skeleton Flail", 0);
            encyclopediaInput.Rows.Add("Skeleton Spear", 0);
            encyclopediaInput.Rows.Add("Red Skeleton", 0);
            encyclopediaInput.Rows.Add("Skeleton Rib", 0);
            encyclopediaInput.Rows.Add("Bone Thrower", 0);
            encyclopediaInput.Rows.Add("Skeleton Ape", 0);
            encyclopediaInput.Rows.Add("Gate Guarder", 0);
            encyclopediaInput.Rows.Add("Golem", 0);
            encyclopediaInput.Rows.Add("Skull Knight", 0);
            encyclopediaInput.Rows.Add("Tiny Devil", 0);
            encyclopediaInput.Rows.Add("Scarecrow", 0);
            encyclopediaInput.Rows.Add("Skeleton Spider", 0);
            encyclopediaInput.Rows.Add("Man-eater", 0);
            encyclopediaInput.Rows.Add("Axe Armor", 0);
            encyclopediaInput.Rows.Add("Witch", 0);
            encyclopediaInput.Rows.Add("Siren", 0);
            encyclopediaInput.Rows.Add("Bomber Armor", 0);
            encyclopediaInput.Rows.Add("Minotaur", 0);
            encyclopediaInput.Rows.Add("Balloon", 0);
            encyclopediaInput.Rows.Add("Big Balloon", 0);
            encyclopediaInput.Rows.Add("Bone Archer", 0);
            encyclopediaInput.Rows.Add("Ruler Sword", 0);
            encyclopediaInput.Rows.Add("Disc Armor", 0);
            encyclopediaInput.Rows.Add("Devil", 0);
            encyclopediaInput.Rows.Add("Merman", 0);
            encyclopediaInput.Rows.Add("Fishman", 0);
            encyclopediaInput.Rows.Add("Arabaki", 0);
            encyclopediaInput.Rows.Add("Ruler Sword Lv2", 0);
            encyclopediaInput.Rows.Add("Feather Demon", 0);
            encyclopediaInput.Rows.Add("Guardian Armor", 0);
            encyclopediaInput.Rows.Add("Boomerang Armor", 0);
            encyclopediaInput.Rows.Add("Giant Merman", 0);
            encyclopediaInput.Rows.Add("Max Slimer", 0);
            encyclopediaInput.Rows.Add("Fleaman Armor", 0);
            encyclopediaInput.Rows.Add("Gold Medusa", 0);
            encyclopediaInput.Rows.Add("Mimic", 0);
            encyclopediaInput.Rows.Add("White Dragon Lv3", 0);
            encyclopediaInput.Rows.Add("Skeleton Mirror", 0);
            encyclopediaInput.Rows.Add("O", 0);
            encyclopediaInput.Rows.Add("Harpy", 0);
            encyclopediaInput.Rows.Add("Axe Armor Lv2", 0);
            encyclopediaInput.Rows.Add("Specter", 0);
            encyclopediaInput.Rows.Add("Bronze Guarder", 0);
            encyclopediaInput.Rows.Add("Peeping Big", 0);
            encyclopediaInput.Rows.Add("Legion (saint)", 0);
            encyclopediaInput.Rows.Add("Shadow", 0);
            encyclopediaInput.Rows.Add("Melty Zombie", 0);
            encyclopediaInput.Rows.Add("Bone Liquid", 0);
            encyclopediaInput.Rows.Add("Ruler Sword Lv3", 0);
            encyclopediaInput.Rows.Add("Poison Lizard", 0);
            encyclopediaInput.Rows.Add("Pazuzu", 0);
            encyclopediaInput.Rows.Add("Spriggan", 0);
            encyclopediaInput.Rows.Add("Gorgon", 0);
            encyclopediaInput.Rows.Add("Blaze Master", 0);
            encyclopediaInput.Rows.Add("Arthro Skeleton", 0);
            encyclopediaInput.Rows.Add("Rare Ghost", 0);
            encyclopediaInput.Rows.Add("Skeleton Glass", 0);
            encyclopediaInput.Rows.Add("Victory Armor", 0);
            encyclopediaInput.Rows.Add("Hammer-Hammer", 0);
            encyclopediaInput.Rows.Add("Disc Armor Lv2", 0);
            encyclopediaInput.Rows.Add("Minotaur Lv2", 0);
            encyclopediaInput.Rows.Add("Legion (corpse)", 0);
            encyclopediaInput.Rows.Add("Thalos", 0);
            encyclopediaInput.Rows.Add("Death", 0);
            encyclopediaInput.Rows.Add("Death", 0);
            encyclopediaInput.Rows.Add("Pixie", 0);
            encyclopediaInput.Rows.Add("Sylph", 0);
            encyclopediaInput.Rows.Add("Master Lizard", 0);
            encyclopediaInput.Rows.Add("Owl", 0);
            encyclopediaInput.Rows.Add("Clear Bone", 0);
            encyclopediaInput.Rows.Add("Jp Bonepillar", 0);
            encyclopediaInput.Rows.Add("Simon Wraith", 0);
            encyclopediaInput.Rows.Add("Pike Master", 0);
            encyclopediaInput.Rows.Add("Cyclops", 0);
            encyclopediaInput.Rows.Add("Maxim", 0);
            encyclopediaInput.Rows.Add("Dracula Wraith", 0);
            encyclopediaInput.Rows.Add("Dracula Wraith", 0);
        }
    }
}
